name: Valgrind Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: install deps
      run: sudo apt-get install valgrind

    - name: run valgrind
      run: |
        make
        valgrind --leak-check=full ./bin/psh

